version: "2"

services:
  web:
    build: .
    volumes:
      - "./Schibsted.Test.BE:/usr/src/app/schibstedApp/Schibsted.Test.BE"
      - "./Schibsted.Test.FE:/usr/src/app/schibstedApp/Schibsted.Test.FE"
    ports:
      - "49160:3000"
      - "4300:4100"
      - "6000:5858"
      - "9875:9876"