version: "2"

services:
  web:
    build: .
    volumes:
      - "./Schibsted.Test.BE:/usr/src/app/schibstedApp/Schibsted.Test.BE"
      - "./Schibsted.Test.FE:/usr/src/app/schibstedApp/Schibsted.Test.FE"
    ports:
      - "5050:5001"
      - "8070:8080"
      - "27017:27017"